// flow-typed signature: 48abe39542c52bf430b7f9dd3285e00c
// flow-typed version: <<STUB>>/next-redirect_v^1.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-redirect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-redirect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'next-redirect/index' {
  declare module.exports: $Exports<'next-redirect'>;
}
declare module 'next-redirect/index.js' {
  declare module.exports: $Exports<'next-redirect'>;
}
