// flow-typed signature: b5ad5869838e13fc360b7cbec38409c2
// flow-typed version: <<STUB>>/react-google-maps_v^8.2.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-maps/lib/addons/InfoBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/addons/MarkerClusterer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/async/withScriptjs' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/addons/InfoBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/addons/MarkerClusterer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/Circle' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/DirectionsRenderer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/drawing/DrawingManager' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/FusionTablesLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/GoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/InfoWindow' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/KmlLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/Marker' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/OverlayView' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/places/SearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/places/StandaloneSearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/Polygon' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/Polyline' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/Rectangle' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/StreetViewPanorama' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/TrafficLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/components/visualization/HeatmapLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/constants' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/drawing/DrawingManager' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/index' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/places/SearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/MapChildHelper' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/OverlayViewHelper' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/visualization/HeatmapLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/withGoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/withScriptjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-maps/lib/addons/InfoBox.js' {
  declare module.exports: $Exports<'react-google-maps/lib/addons/InfoBox'>;
}
declare module 'react-google-maps/lib/addons/MarkerClusterer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/addons/MarkerClusterer'>;
}
declare module 'react-google-maps/lib/async/withScriptjs.js' {
  declare module.exports: $Exports<'react-google-maps/lib/async/withScriptjs'>;
}
declare module 'react-google-maps/lib/components/addons/InfoBox.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/addons/InfoBox'>;
}
declare module 'react-google-maps/lib/components/addons/MarkerClusterer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/addons/MarkerClusterer'>;
}
declare module 'react-google-maps/lib/components/Circle.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/Circle'>;
}
declare module 'react-google-maps/lib/components/DirectionsRenderer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/DirectionsRenderer'>;
}
declare module 'react-google-maps/lib/components/drawing/DrawingManager.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/drawing/DrawingManager'>;
}
declare module 'react-google-maps/lib/components/FusionTablesLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/FusionTablesLayer'>;
}
declare module 'react-google-maps/lib/components/GoogleMap.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/GoogleMap'>;
}
declare module 'react-google-maps/lib/components/InfoWindow.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/InfoWindow'>;
}
declare module 'react-google-maps/lib/components/KmlLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/KmlLayer'>;
}
declare module 'react-google-maps/lib/components/Marker.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/Marker'>;
}
declare module 'react-google-maps/lib/components/OverlayView.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/OverlayView'>;
}
declare module 'react-google-maps/lib/components/places/SearchBox.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/places/SearchBox'>;
}
declare module 'react-google-maps/lib/components/places/StandaloneSearchBox.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/places/StandaloneSearchBox'>;
}
declare module 'react-google-maps/lib/components/Polygon.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/Polygon'>;
}
declare module 'react-google-maps/lib/components/Polyline.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/Polyline'>;
}
declare module 'react-google-maps/lib/components/Rectangle.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/Rectangle'>;
}
declare module 'react-google-maps/lib/components/StreetViewPanorama.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/StreetViewPanorama'>;
}
declare module 'react-google-maps/lib/components/TrafficLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/TrafficLayer'>;
}
declare module 'react-google-maps/lib/components/visualization/HeatmapLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/components/visualization/HeatmapLayer'>;
}
declare module 'react-google-maps/lib/constants.js' {
  declare module.exports: $Exports<'react-google-maps/lib/constants'>;
}
declare module 'react-google-maps/lib/drawing/DrawingManager.js' {
  declare module.exports: $Exports<'react-google-maps/lib/drawing/DrawingManager'>;
}
declare module 'react-google-maps/lib/index.js' {
  declare module.exports: $Exports<'react-google-maps/lib/index'>;
}
declare module 'react-google-maps/lib/places/SearchBox.js' {
  declare module.exports: $Exports<'react-google-maps/lib/places/SearchBox'>;
}
declare module 'react-google-maps/lib/utils/MapChildHelper.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/MapChildHelper'>;
}
declare module 'react-google-maps/lib/utils/OverlayViewHelper.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/OverlayViewHelper'>;
}
declare module 'react-google-maps/lib/visualization/HeatmapLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/visualization/HeatmapLayer'>;
}
declare module 'react-google-maps/lib/withGoogleMap.js' {
  declare module.exports: $Exports<'react-google-maps/lib/withGoogleMap'>;
}
declare module 'react-google-maps/lib/withScriptjs.js' {
  declare module.exports: $Exports<'react-google-maps/lib/withScriptjs'>;
}
